apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wxhg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wxhg
    app.kubernetes.io/part-of: byoc-app-gmxo
  name: wxhg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: wxhg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: wxhg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-icst-tenant/byoc-app-gmxo/wxhg@sha256:799f8cce90110c6f82f9a689fe64750a8b97de75e937016c59f143e4e7024f6e
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
