apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wxhg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wxhg
    app.kubernetes.io/part-of: byoc-app-gmxo
  name: wxhg
spec:
  rules:
  - host: wxhg-byoc-icst-tenant.apps.eee2528eeb6362cd6978.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: wxhg
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
